#source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'SwiftDemo_Example' do
  pod 'SwiftDemo', :path => '../'

  target 'SwiftDemo_Tests' do
    inherit! :search_paths

#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
